---
- name: User creation using loop
  hosts: web
  become: yes

  tasks:
    - name: "Create users: user1, user2, user3, user4"
      user:
        name: "{{ item }}"
        state: present
      loop:
        - user1
        - user2
        - user3
        - user4
