- name: Install Apache # name of the playbook
  hosts: web # target
  become: yes # Needs sudo/administrator access

  tasks:
    - name: Apache installation
      dnf:
        name: httpd
        state: present

    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started
