
- name: Install Apache # Name of the playbook
  hosts: web           # Target group defined in your inventory
  become: yes          # Use privilege escalation (sudo)

  tasks:
    - name: Install Apache package
      dnf:
        name: httpd
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index.html to web root with correct permissions
      copy:
        src: /home/ec2-user/learning/index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
